language: node_js
node_js:
  - 10
cache: yarn
branches:
  only:
    - source
script:
  - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  target_branch: master
  on:
    branch: source
